### ISSUE TITLE
hope jcenter repositories

### ISSUE THREAD

**Issue by jp1017** [fatangare/LogcatViewer#1]
How to use it in gradle?

**Comment by fatangare** [comment]
1. Add following code to your project's build.gradle - To add library to build process
   `compile project(':logcatviewer');`
2. Add following code to your project's settings.gradle - To make logcatviewer and standout as modules in your project.
   `include ':logcatviewer', ':standOut'`

**Comment by jp1017** [comment]
Yeah, I know this, thanks.
But I just what to use it in gradle only not include the project (':logcatviewer'), just like: 

```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile "jcenter repositories library"
}
```

**Comment by fatangare** [comment]
Aha you mean maven repo.... I am new to this area...still struggling to upload to maven repo. :(

**Comment by jp1017** [comment]
Yeap！
GOGOGO.

**Comment by fatangare** [comment]
Use `compile 'com.github.fatangare.LogcatViewer:logcatviewer:aadf092447'`

**Comment by jp1017** [comment]
cool, thanks.
